### ISSUE TITLE
显存不断累加问题

### ISSUE THREAD

**Issue by bugsuse** [coolsunxu/MIM_Pytorch#1]
应用到moving mnist/radar echo数据集时，显存会不断的累加

**Comment by coolsunxu** [comment]
额，我看了原作者的论文，就写了个pytorch版本的，并没有跑过相关实验。。。。。。

**Comment by coolsunxu** [comment]
> 
> 
> 应用到moving mnist/radar echo数据集时，显存会不断的累加

额，我看了原作者的论文，就写了个pytorch版本的，并没有跑过相关实验。。。。。。

**Comment by bugsuse** [comment]
> > 应用到moving mnist/radar echo数据集时，显存会不断的累加
> 
> 额，我看了原作者的论文，就写了个pytorch版本的，并没有跑过相关实验。。。。。。

你是按照tf的代码复现的吗

**Comment by coolsunxu** [comment]
> 
> 
> > > 应用到moving mnist/radar echo数据集时，显存会不断的累加
> > 
> > 
> > 额，我看了原作者的论文，就写了个pytorch版本的，并没有跑过相关实验。。。。。。
> 
> 你是按照tf的代码复现的吗

对的

**Comment by bugsuse** [comment]
> > > > 应用到moving mnist/radar echo数据集时，显存会不断的累加
> > > 
> > > 
> > > 额，我看了原作者的论文，就写了个pytorch版本的，并没有跑过相关实验。。。。。。
> > 
> > 
> > 你是按照tf的代码复现的吗
> 
> 对的

感觉直接移植可能有些细节还是会有问题
